//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DYC_FinalYr_.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddComplainInDatabaseTable
    {
        public int Id { get; set; }
        public string ComplainCataegory { get; set; }
        public string ComplainArea { get; set; }
        public string RoadNumber { get; set; }
        public string ComplainDeatils { get; set; }
        public string Photo { get; set; }
        public string ComplainerName { get; set; }
        public string ContractNumber { get; set; }
        public string Email { get; set; }
    }
}
